"""add movie popularity

Revision ID: 98a7885d7eea
Revises: e0f3a409fb6c
Create Date: 2026-08-01 18:11:15.061161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a7885d7eea'
down_revision: Union[str, Sequence[str], None] = 'e0f3a409fb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('popularity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'popularity')
    # ### end Alembic commands ###
