"""add movie detail fields

Revision ID: e0f3a409fb6c
Revises: 05647ae2923a
Create Date: 2026-08-01 17:35:58.180183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f3a409fb6c'
down_revision: Union[str, Sequence[str], None] = '05647ae2923a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('backdrop_url', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('vote_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'vote_count')
    op.drop_column('movies', 'vote_average')
    op.drop_column('movies', 'backdrop_url')
    op.drop_column('movies', 'tagline')
    # ### end Alembic commands ###
